import jwt from 'jsonwebtoken';
import env from 'dotenv';

env.config();


const authToken = (req, res, next) => {
    const token = req.body.token || req.query.token || req.headers['x-access-token'];
    // decode the token generated by user payload during signin or signup
    if (token) {
      jwt.verify(token, process.env.SECRET_KEY, (err, decoded) => {
        if (err) {
          return res.json({
            status: 'Failed',
            message: 'Authentication failed. Token is either invalid or expired'
          }).status(401);
        } else {
          req.decoded = decoded;
         return next();
        }
      });
    } else {
      return res.json({
        status: 'Failed',
        message: 'wrong token. provide  a valid token'
      }).status(403);
    }
  };

export default authToken;